### ISSUE TITLE
Why don't you include LiberationMono-Regular.ttf?

### ISSUE THREAD

**Issue by tn1997tn** [ec429/libatg#7]
So people will not have to install that font.

**Comment by ec429** [comment]
Because vendoring of dependencies into something that is itself a dynamically-linked dependency is inappropriate.

The correct way to handle this is for programs which vendor libatg to also vendor the font, while programs for which libatg is an external dependency should rely on the same dependency mechanism (e.g. package management systems) to pull in the font as well.

If this presents a problem for you, please elaborate on your use-case/situation and why neither of these solutions is suitable.
